# Generated by Django 4.2.7 on 2023-11-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="content",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="synopsis",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="title",
            field=models.CharField(default="test", max_length=200),
            preserve_default=False,
        ),
    ]
