# Generated by Django 4.2.7 on 2023-11-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_content_blog_synopsis_blog_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="blogs",
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(blank=True, to="blog.tag"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.CharField(blank=True, default="hanshoi", max_length=100),
        ),
        migrations.AlterField(
            model_name="blog",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="date modified"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="published",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date published"
            ),
        ),
    ]
