# Generated by Django 4.2.7 on 2023-11-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=128),
        ),
    ]
